- name: Dowload zabbix release package
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb

- name: Install zabbix-agent2 packages
  apt:
    name: 
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present
    update_cache: yes

- name: Set Server IP
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: 'Server=127.0.0.1'
    line: "Server=127.0.0.1,{{zabbix_server_ip}}"

- name: Set ActiveServer IP
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: 'ServerActive=127.0.0.1'
    line: "ServerActive=127.0.0.1,{{zabbix_server_ip}}"

- name: Absent Hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: 'Hostname='
    state: absent

- name: Set HostMetadata
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '# HostMetadata='
    line: "HostMetadata={{host_metadata}}"

- name: Stop zabbix-agent2
  service:
    name: zabbix-agent2
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Start zabbix-agent2
  service:
    name: zabbix-agent2
    state: started
    enabled: yes
