- name: Installs haproxy
  apt:
    name:
      - haproxy
    state: present
    update_cache: true

- name: Pushes configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: root
    group: root

- name: Sets default starting flag to 1
  lineinfile:
    path: /etc/default/haproxy
    regexp: "^ENABLED"
    line: "ENABLED=1"
    #create: yes
  notify: 
    - restart_haproxy

